---
- hosts: localhost
  tasks:
    - name: Configure XDG
      copy:
        src: ./files/.xfce/xdg
        dest: /home/zubmic/.config
        owner: zubmic

    - name: Configure XFCE
      copy:
        src: ./files/.xfce/xfce4
        dest: /home/zubmic/.config/
        owner: zubmic

    - name: Configure Thunar
      copy:
        src: ./files/.xfce/Thunar
        dest: /home/zubmic/.config/
        owner: zubmic

    - name:  Installing Thunderbird
      apt:
        name: thunderbird
        state: latest

    - name: Installing KeePass2
      apt:
        name: keepass2
        state: latest

    - name: Installing Gimp
      apt:
        name: gimp
        state: latest

    - name: Installing Vim
      apt:
        name: vim
        state: latest

    - name: Installing Pidgin
      apt:
        name: pidgin
        state: latest

    - name: Installing Calibre
      apt:
        name: calibre
        state: latest

    - name: Configure Calibre
      copy:
        src: ./files/calibre
        dest: /home/zubmic/.config
        owner: zubmic

    - name: Installing LibreOffice
      apt:
        name: libreoffice
        state: latest

    - name: Installing TeXworks
      apt:
        name: texworks
        state: latest

    - name: Installing Midnight Commander
      apt:
        name: mc
        state: latest

    - name: Installing Pomodoro Clock
      apt:
        name: gnome-shell-pomodoro
        state: latest
        install_recommends: yes

    - name: Installing Audacious
      apt:
        name: audacious
        state: latest

    - name: Installing Visual Studio Code
      apt:
        deb: https://go.microsoft.com/fwlink/?LinkID=760868

    - name: Installing Virtualbox
      apt:
        deb: https://download.virtualbox.org/virtualbox/6.1.10/virtualbox-6.1_6.1.10-138449~Debian~buster_amd64.deb
