---

# Run it as root to fix temporary files permission issue happening in the following block
- name: Configure window bar
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    state: present
    value: "':minimize,maximize,close'"
  become: yes

- block:
  - name: Configure window bar
    dconf:
      key: "/org/gnome/desktop/wm/preferences/button-layout"
      state: present
      value: "':minimize,maximize,close'"

  - name: Configure the background picture
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      state: present
      value: "'file:///usr/share/desktop-base/lines-theme/wallpaper/gnome-background.xml'"

  - name: Configure cursor theme
    dconf:
      key: "/org/gnome/desktop/interface/cursor-theme"
      state: present
      value: "'DMZ-White'"

  - name: Configure icon theme
    dconf:
      key: "/org/gnome/desktop/interface/icon-theme"
      state: present
      value: "'gnome-dust'"
  become_user: "{ desktop_user }"